# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: PipelineNetProject
  displayName: Pipeline .Net Project
  jobs:
  - job: PipelineWebApi
    steps:
    - task: PowerShell@2
      displayName: Build Net Api $(ProjectName) $(Version)
      inputs:
        filePath: './BuildNetApi.ps1'
        arguments: './BuildNetApi.ps1; CIBuildNetApi'
      timeoutInMinutes: 10
      continueOnError: false
