version: '3.4'

services:
  courses.api:
    image: courses-api
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      TZ: America/Sao_Paulo
      ConnectionStringSqlServer: "ConnectionStringSqlServer"
      ASPNETCORE_ENVIRONMENT: "Development"